export const siteConfig = {
  name: "خطوة لنقل الأثاث",
  shortName: "خطوة",
  description:
    "خطوة لنقل الأثاث - أفضل شركة نقل أثاث في مصر متخصصة في التجمع الخامس، مدينتي، الشيخ زايد، 6 أكتوبر، والقاهرة الجديدة. خدمة احترافية 24/7 مع فرق مدربة، تغليف احترافي، ونش رفع، وضمان كامل على المقتنيات. اتصل الآن للحصول على عرض سعر مجاني.",
  url: "https://khatwamoving.com",
  phone: "01042532253",
  phoneIntl: "+201042532253",
  whatsapp: "201042532253",
  email: "koutwaa722@gmail.com",
  address: "التجمع الخامس - القاهرة الجديدة - مصر",
  addressEn: "Fifth Settlement, New Cairo, Egypt",
  city: "القاهرة الجديدة",
  region: "القاهرة",
  postalCode: "11835",
  country: "مصر",
  countryCode: "EG",
  serviceArea: "جميع محافظات مصر",
  yearsOfExperience: 10,
  foundingYear: 2014,
  coordinates: {
    latitude: 30.0131,
    longitude: 31.4961,
  },
  ratings: {
    value: 4.9,
    count: 500,
    best: 5,
  },
  socialMedia: {
    facebook: "",
    instagram: "",
    tiktok: "",
    youtube: "",
  },
  businessHours: {
    open: "00:00",
    close: "23:59",
    days: ["Sat", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri"],
  },
} as const;